import Head from "next/head";
import { Libre_Franklin } from "next/font/google";
import localFont from "next/font/local";

export const libre = Libre_Franklin({ subsets: ["latin"] });
export const levi = localFont({ src: "../assets/leviwindows.ttf" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${libre.className} ${levi.className}`}></div>
    </>
  );
}
