import type { Metadata } from "next";
import { Global } from "@emotion/react";
import { globalStyle } from "@/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Global styles={globalStyle} />
      <body>{children}</body>
    </html>
  );
}
