import type { Metadata } from "next";

import { Libre_Franklin } from "next/font/google";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const libre = Libre_Franklin();
export const levi = localFont({ src: "../assets/leviwindows.ttf" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={levi.className}>
      <body>{children}</body>
    </html>
  );
}
